export interface WordEntry {
  word: string;
  clue: string;
}

// All words must be UPPERCASE letters only (no numbers or symbols)
export const WORD_BANK: WordEntry[] = [
  // ── 3-letter ──────────────────────────────────────────────────────────────
  { word: 'GAS',       clue: 'Fee paid for blockchain transactions' },
  { word: 'NFT',       clue: 'Non-Fungible Token (abbr.)' },
  { word: 'DAO',       clue: 'Decentralized Autonomous Organization (abbr.)' },
  { word: 'ETH',       clue: 'Native currency of Ethereum' },
  { word: 'DEX',       clue: 'Decentralized exchange (abbr.)' },
  { word: 'CEX',       clue: 'Centralized exchange (abbr.)' },
  { word: 'APY',       clue: 'Annual percentage yield (abbr.)' },
  { word: 'TVL',       clue: 'Total value locked in a protocol (abbr.)' },
  { word: 'MEV',       clue: 'Value extracted by reordering txs (abbr.)' },
  { word: 'EVM',       clue: 'Ethereum Virtual Machine (abbr.)' },
  { word: 'ABI',       clue: 'Smart contract interface spec (abbr.)' },
  { word: 'RPC',       clue: 'Node communication protocol (abbr.)' },
  { word: 'ENS',       clue: 'Ethereum Name Service (abbr.)' },
  { word: 'RUG',       clue: 'Liquidity pull that wipes a token (slang)' },
  { word: 'FEE',       clue: 'Cost charged per transaction' },
  { word: 'KEY',       clue: 'Cryptographic secret for signing txs' },
  { word: 'AMM',       clue: 'Automated market maker (abbr.)' },
  { word: 'ICO',       clue: 'Token sale to the public (abbr.)' },
  { word: 'IEO',       clue: 'Exchange-hosted token sale (abbr.)' },
  { word: 'IDO',       clue: 'Token launch on a DEX (abbr.)' },
  { word: 'KYC',       clue: 'Identity verification requirement (abbr.)' },
  { word: 'AML',       clue: 'Financial crime compliance framework (abbr.)' },
  { word: 'DID',       clue: 'Decentralized identifier standard (abbr.)' },
  { word: 'EOA',       clue: 'User-controlled wallet account type (abbr.)' },
  { word: 'SBT',       clue: 'Non-transferable identity token (abbr.)' },
  { word: 'ERC',       clue: 'Ethereum token standard prefix (abbr.)' },
  { word: 'POW',       clue: 'Mining-based consensus mechanism (abbr.)' },
  { word: 'POS',       clue: 'Staking-based consensus mechanism (abbr.)' },
  { word: 'API',       clue: 'Software communication interface (abbr.)' },
  { word: 'SDK',       clue: 'Developer toolkit for building dApps (abbr.)' },
  { word: 'APR',       clue: 'Annual percentage rate (abbr.)' },
  { word: 'ATH',       clue: 'Record highest price ever reached (abbr.)' },
  { word: 'ATL',       clue: 'Lowest price ever recorded (abbr.)' },
  { word: 'FUD',       clue: 'Fear, Uncertainty, Doubt spread to tank prices' },
  { word: 'ARB',       clue: 'Profiting from price gaps across venues' },
  { word: 'BOT',       clue: 'Automated program that trades or snipes txs' },
  { word: 'HEX',       clue: 'Base-16 encoding used for addresses and data' },
  { word: 'ROI',       clue: 'Return on investment (abbr.)' },
  { word: 'TPS',       clue: 'Measure of blockchain throughput (abbr.)' },
  { word: 'GMI',       clue: 'Gonna Make It — crypto optimist motto (abbr.)' },

  // ── 4-letter ──────────────────────────────────────────────────────────────
  { word: 'BASE',      clue: "Coinbase's L2 blockchain" },
  { word: 'MINT',      clue: 'Create a new NFT or token' },
  { word: 'SWAP',      clue: 'Exchange one token for another' },
  { word: 'POOL',      clue: 'Liquidity reserve for trading' },
  { word: 'EARN',      clue: 'Generate yield from crypto assets' },
  { word: 'BURN',      clue: 'Permanently destroy tokens' },
  { word: 'FORK',      clue: 'Split a blockchain into two chains' },
  { word: 'NODE',      clue: 'Network participant that validates txs' },
  { word: 'LOCK',      clue: 'Time-restrict access to tokens' },
  { word: 'BOND',      clue: 'Protocol-owned liquidity mechanism' },
  { word: 'VOTE',      clue: 'Governance action with locked tokens' },
  { word: 'WRAP',      clue: 'Tokenize a native asset (e.g. WETH)' },
  { word: 'PUMP',      clue: 'Sharp coordinated price increase (slang)' },
  { word: 'DUMP',      clue: 'Mass sell-off of a token (slang)' },
  { word: 'COLD',      clue: '___ wallet: offline key storage' },
  { word: 'SEED',      clue: 'Recovery phrase for a wallet' },
  { word: 'HASH',      clue: 'Cryptographic fingerprint of data' },
  { word: 'SAFE',      clue: 'Popular multisig wallet contract' },
  { word: 'DEFI',      clue: 'Decentralized Finance (abbr.)' },
  { word: 'HODL',      clue: 'Hold crypto no matter what (slang)' },
  { word: 'MEME',      clue: 'Viral token driven by internet culture' },
  { word: 'SIGN',      clue: 'Authorize a transaction with a private key' },
  { word: 'DROP',      clue: 'Short for airdrop' },
  { word: 'EMIT',      clue: 'Broadcast a contract event on-chain' },
  { word: 'FIAT',      clue: 'Government-issued currency (e.g. USD)' },
  { word: 'BULL',      clue: 'Optimistic market trend pushing prices up' },
  { word: 'BEAR',      clue: 'Pessimistic market trend pushing prices down' },
  { word: 'MOON',      clue: 'Price going parabolic upward (slang)' },
  { word: 'REKT',      clue: 'Suffered heavy trading losses (slang)' },
  { word: 'FOMO',      clue: 'Anxiety of missing a price move (abbr.)' },
  { word: 'DYOR',      clue: 'Do Your Own Research (abbr.)' },
  { word: 'ANON',      clue: 'Pseudonymous user or developer' },
  { word: 'FARM',      clue: 'Earn yield by providing protocol liquidity' },
  { word: 'SPOT',      clue: '___ market: buy or sell at the current price' },
  { word: 'LONG',      clue: 'Bet that an asset price will rise' },
  { word: 'LEND',      clue: 'Supply assets to a lending protocol' },
  { word: 'FLIP',      clue: 'Buy and quickly resell an NFT for profit' },
  { word: 'DAPP',      clue: 'Decentralized application (abbr.)' },
  { word: 'APES',      clue: 'Jumps into a trade without research (slang)' },
  { word: 'WETH',      clue: 'ERC-20 version of native ETH' },
  { word: 'HOLD',      clue: 'Keep tokens without selling' },
  { word: 'SELL',      clue: 'Exit a crypto position for another asset' },
  { word: 'COPE',      clue: 'Denial after a losing trade (slang)' },
  { word: 'CHAD',      clue: 'Fearless high-conviction trader (slang)' },
  { word: 'NGMI',      clue: 'Not Gonna Make It — crypto pessimist (abbr.)' },
  { word: 'SAFU',      clue: 'Crypto slang meaning funds are completely safe' },
  { word: 'AAVE',      clue: 'Leading decentralized lending protocol' },
  { word: 'CALL',      clue: 'Invoke a smart contract function' },

  // ── 5-letter ──────────────────────────────────────────────────────────────
  { word: 'DEGEN',     clue: 'High-risk crypto trader (slang)' },
  { word: 'YIELD',     clue: 'Return earned from staking or lending' },
  { word: 'STAKE',     clue: 'Lock tokens to earn rewards' },
  { word: 'TOKEN',     clue: 'Digital asset on a blockchain' },
  { word: 'VAULT',     clue: 'Smart contract that holds funds securely' },
  { word: 'CHAIN',     clue: 'Sequence of linked transaction blocks' },
  { word: 'LAYER',     clue: '___ 2: scaling solution built on L1' },
  { word: 'PROXY',     clue: 'Upgradeable smart contract pattern' },
  { word: 'AUDIT',     clue: 'Security review of smart contract code' },
  { word: 'WHALE',     clue: 'Holder of an enormous amount of crypto' },
  { word: 'NONCE',     clue: 'Number used once for transaction ordering' },
  { word: 'BLOCK',     clue: 'Bundle of transactions added to the chain' },
  { word: 'PROOF',     clue: '___ of stake: consensus mechanism' },
  { word: 'CLAIM',     clue: 'Collect an airdrop or protocol reward' },
  { word: 'RELAY',     clue: 'Gasless transaction forwarder service' },
  { word: 'AURA',      clue: 'Onchain identity score on Base' },
  { word: 'SHORT',     clue: 'Bet that an asset price will fall' },
  { word: 'FLASH',     clue: '___ loan: uncollateralized intra-tx loan' },
  { word: 'ALPHA',     clue: 'Exclusive market edge or insider info (slang)' },
  { word: 'DELTA',     clue: 'Price change sensitivity in options trading' },
  { word: 'CURVE',     clue: 'AMM protocol optimized for stablecoins' },
  { word: 'BRIBE',     clue: 'Token incentive to direct governance votes' },
  { word: 'EPOCH',     clue: 'Fixed time window in a staking protocol' },
  { word: 'FLOOR',     clue: 'Minimum price of an NFT collection' },
  { word: 'SWEEP',     clue: 'Buy all NFTs at the floor price at once' },
  { word: 'MAKER',     clue: 'Liquidity provider who sets limit orders' },
  { word: 'TAKER',     clue: 'Trader who fills an existing order' },
  { word: 'TRADE',     clue: 'Buy or sell a crypto asset' },
  { word: 'PANIC',     clue: '___ sell: dump tokens out of fear' },
  { word: 'RALLY',     clue: 'Sustained upward price movement' },
  { word: 'GRANT',     clue: 'Funding awarded by a DAO to developers' },
  { word: 'CROSS',     clue: '___ chain: operating across multiple networks' },
  { word: 'SHILL',     clue: 'Aggressively promote a token for profit' },
  { word: 'PAPER',     clue: '___ hands: selling at the first sign of loss' },
  { word: 'SNIPE',     clue: 'Instantly grab a listing or front-run a tx' },
  { word: 'MINER',     clue: 'Proof-of-Work block producer' },
  { word: 'SHARD',     clue: 'Parallel segment of a sharded blockchain' },
  { word: 'ETHER',     clue: 'The native fuel and currency of Ethereum' },
  { word: 'UNCLE',     clue: 'Orphaned block valid but excluded from the PoW chain' },
  { word: 'QUANT',     clue: 'Algorithmic, data-driven trading strategy' },
  { word: 'CRASH',     clue: 'Rapid severe drop in market prices' },
  { word: 'RATIO',     clue: 'Collateral-to-debt proportion in DeFi' },
  { word: 'REPAY',     clue: 'Return borrowed assets to a lending protocol' },
  { word: 'ENTRY',     clue: 'Price level at which a position is opened' },
  { word: 'TRAIT',     clue: 'Attribute that determines an NFT rarity' },
  { word: 'EVENT',     clue: 'On-chain log emitted by a smart contract' },

  // ── 6-letter ──────────────────────────────────────────────────────────────
  { word: 'WALLET',    clue: 'Software that stores your crypto keys' },
  { word: 'BRIDGE',    clue: 'Move assets between blockchains' },
  { word: 'DEPLOY',    clue: 'Publish a smart contract to the chain' },
  { word: 'PERMIT',    clue: 'Gasless token approval via signature' },
  { word: 'REVOKE',    clue: 'Cancel a token spending approval' },
  { word: 'ORACLE',    clue: 'Off-chain data feed for smart contracts' },
  { word: 'ROLLUP',    clue: 'L2 that batches txs and posts proofs to L1' },
  { word: 'ESCROW',    clue: 'Contract holding funds until conditions met' },
  { word: 'REWARD',    clue: 'Incentive paid to stakers or validators' },
  { word: 'FAUCET',    clue: 'Testnet dispenser of free tokens' },
  { word: 'STAKER',    clue: 'One who locks tokens for yield' },
  { word: 'SIGNER',    clue: 'Address authorized to sign transactions' },
  { word: 'MERKLE',    clue: '___ tree: data structure for inclusion proofs' },
  { word: 'KEEPER',    clue: 'Bot that triggers protocol maintenance functions' },
  { word: 'BURNER',    clue: 'Disposable wallet used for privacy' },
  { word: 'MARGIN',    clue: 'Borrowed capital used in leveraged trading' },
  { word: 'QUORUM',    clue: 'Minimum vote threshold for a proposal to pass' },
  { word: 'MINTER',    clue: 'Address with permission to create new tokens' },
  { word: 'LENDER',    clue: 'Protocol or user that supplies loanable assets' },
  { word: 'BORROW',    clue: 'Take a loan against posted collateral' },
  { word: 'TRADER',    clue: 'Active buyer and seller of crypto assets' },
  { word: 'SENDER',    clue: 'Originating address of a blockchain tx' },
  { word: 'SUPPLY',    clue: 'Total or circulating amount of a token' },
  { word: 'MARKET',    clue: 'Venue or order type for buying and selling' },
  { word: 'PAYOUT',    clue: 'Distribution of earned rewards to users' },
  { word: 'REBASE',    clue: 'Elastic supply adjustment of an algorithmic token' },
  { word: 'REDEEM',    clue: 'Exchange a receipt token for the underlying asset' },
  { word: 'REFUND',    clue: 'Gas returned for unused computation in a tx' },
  { word: 'VESTED',    clue: 'Tokens released after a lockup period' },
  { word: 'PUBLIC',    clue: '___ key: shareable cryptographic identifier' },
  { word: 'CANDLE',    clue: 'OHLC bar on a price chart' },
  { word: 'BALLOT',    clue: 'On-chain vote cast in a governance round' },
  { word: 'ROUTER',    clue: 'Contract that finds the optimal swap path' },
  { word: 'STABLE',    clue: 'Price-pegged crypto asset class' },
  { word: 'PAUSER',    clue: 'Role with authority to halt a smart contract' },
  { word: 'LOCKER',    clue: 'Contract that time-locks tokens until maturity' },
  { word: 'PROVER',    clue: 'Entity that generates a zero-knowledge proof' },
  { word: 'REBATE',    clue: 'Partial fee refund returned to a trader' },
  { word: 'FROZEN',    clue: 'Account blocked from sending tokens' },
  { word: 'CALLER',    clue: 'Address that invokes a smart contract function' },
  { word: 'VOTING',    clue: 'Governance participation weighted by tokens held' },
  { word: 'REVERT',    clue: 'Transaction failure that rolls back all changes' },
  { word: 'REVEAL',    clue: 'Moment when NFT metadata is made public' },
  { word: 'RARITY',    clue: 'Scarcity score of an NFT based on its traits' },
  { word: 'HOLDER',    clue: 'Owner of a token or NFT' },
  { word: 'OPCODE',    clue: 'Low-level instruction executed by the EVM' },
  { word: 'ENCODE',    clue: 'Pack data into ABI format for a contract call' },
  { word: 'DECODE',    clue: 'Unpack ABI-encoded contract return data' },
  { word: 'STRUCT',    clue: 'Custom data type grouping fields in Solidity' },
  { word: 'ASSERT',    clue: 'Solidity check that reverts on invariant breach' },
  { word: 'POOLED',    clue: 'Assets combined into a shared liquidity fund' },

  // ── 7-letter ──────────────────────────────────────────────────────────────
  { word: 'AIRDROP',   clue: 'Free token distribution to eligible holders' },
  { word: 'ONCHAIN',   clue: 'Stored or executed on a blockchain' },
  { word: 'TESTNET',   clue: 'Sandbox blockchain for development' },
  { word: 'MAINNET',   clue: 'Live production blockchain network' },
  { word: 'GENESIS',   clue: 'The very first block of a blockchain' },
  { word: 'MEMPOOL',   clue: 'Queue of pending unconfirmed transactions' },
  { word: 'VESTING',   clue: 'Token release schedule over time' },
  { word: 'HARVEST',   clue: 'Claim accumulated yield from a farm' },
  { word: 'RESERVE',   clue: 'Assets held by a protocol as a safety buffer' },
  { word: 'EXECUTE',   clue: 'Run a smart contract function on-chain' },
  { word: 'PROPOSE',   clue: 'Submit a new governance proposal to a DAO' },
  { word: 'MIGRATE',   clue: 'Move state or funds to a new contract version' },
  { word: 'NETWORK',   clue: 'The peer-to-peer system underlying a blockchain' },
  { word: 'ADDRESS',   clue: 'Unique identifier for a wallet or contract' },
  { word: 'RECEIVE',   clue: 'Fallback function that accepts incoming ETH' },
  { word: 'STORAGE',   clue: 'Persistent on-chain state of a smart contract' },
  { word: 'UPGRADE',   clue: 'Replace a proxy implementation with a new one' },
  { word: 'DEPOSIT',   clue: 'Lock tokens into a protocol to start earning' },
  { word: 'BALANCE',   clue: 'Amount of tokens held at a given address' },
  { word: 'DISPUTE',   clue: 'Challenge a state root in an optimistic rollup' },
  { word: 'LISTING',   clue: 'Adding a token to an exchange or marketplace' },
  { word: 'PRIVATE',   clue: '___ key: secret cryptographic signing key' },
  { word: 'PAYLOAD',   clue: 'Data bytes carried inside a transaction' },
  { word: 'COMPUTE',   clue: 'Off-chain calculation submitted for on-chain use' },
  { word: 'BUILDER',   clue: 'MEV entity that constructs optimized blocks' },
  { word: 'BATCHER',   clue: 'Rollup component that bundles txs for L1' },
  { word: 'BUNDLER',   clue: 'ERC-4337 node that packages UserOperations' },
  { word: 'ACCOUNT',   clue: 'On-chain identity in account abstraction' },
  { word: 'SLASHED',   clue: 'Had stake confiscated for validator misbehavior' },
  { word: 'CONVERT',   clue: 'Exchange one token denomination for another' },
  { word: 'STAKING',   clue: 'Locking tokens to secure a network for yield' },
  { word: 'LENDING',   clue: 'Supplying assets to a money-market protocol' },
  { word: 'FARMING',   clue: 'Providing liquidity to earn protocol incentives' },
  { word: 'MINTING',   clue: 'Creating new NFTs or tokens on-chain' },
  { word: 'TRADING',   clue: 'Actively buying and selling crypto assets' },
  { word: 'FUNDING',   clue: '___ rate: periodic payment between longs and shorts' },
  { word: 'WRAPPED',   clue: 'Native asset tokenized as an ERC-20' },
  { word: 'ROYALTY',   clue: 'Creator fee paid on each NFT secondary sale' },
  { word: 'MAPPING',   clue: 'Key-value data structure in Solidity' },
  { word: 'LIBRARY',   clue: 'Reusable deployed Solidity code module' },
  { word: 'REQUIRE',   clue: 'Solidity guard that reverts if condition fails' },
  { word: 'SETTLED',   clue: 'Transaction finalized and irreversible on-chain' },
  { word: 'CLAIMED',   clue: 'Airdrop or reward that has already been collected' },

  // ── 8-letter ──────────────────────────────────────────────────────────────
  { word: 'ETHEREUM',  clue: 'The second-largest smart contract platform' },
  { word: 'SNAPSHOT',  clue: 'Record of balances at a specific block' },
  { word: 'MULTISIG',  clue: 'Wallet requiring multiple signers to approve' },
  { word: 'BYTECODE',  clue: 'Compiled EVM smart contract instructions' },
  { word: 'APPROVAL',  clue: 'Permission granted to spend your tokens' },
  { word: 'WITHDRAW',  clue: 'Remove deposited tokens from a protocol' },
  { word: 'CALLDATA',  clue: 'Input data bytes passed to a contract call' },
  { word: 'TIMELOCK',  clue: 'Enforced delay before executing a governance action' },
  { word: 'OFFCHAIN',  clue: 'Computed or stored outside the blockchain' },
  { word: 'SLIPPAGE',  clue: 'Price difference between quote and execution' },
  { word: 'TRANSFER',  clue: 'Move tokens from one address to another' },
  { word: 'DELEGATE',  clue: 'Assign your voting power to another address' },
  { word: 'EMISSION',  clue: 'Rate at which new tokens enter circulation' },
  { word: 'TREASURY',  clue: 'Protocol-owned fund for grants and development' },
  { word: 'CONTRACT',  clue: 'Self-executing code deployed on a blockchain' },
  { word: 'PROPOSAL',  clue: 'Governance action submitted for DAO voting' },
  { word: 'FINALITY',  clue: 'Point at which a block cannot be reversed' },
  { word: 'VERIFIED',  clue: 'Contract whose source matches deployed bytecode' },
  { word: 'FALLBACK',  clue: 'Contract function called when no selector matches' },
  { word: 'VERIFIER',  clue: 'Contract that validates a zero-knowledge proof' },
  { word: 'LEVERAGE',  clue: 'Borrowed capital multiplier in a trade' },
  { word: 'METADATA',  clue: 'Off-chain data describing an NFT' },
  { word: 'POSITION',  clue: 'Open long or short in a DeFi protocol' },
  { word: 'INTEREST',  clue: 'Rate paid on borrowed assets in a lending market' },
  { word: 'MODIFIER',  clue: 'Solidity function guard that gates execution' },
  { word: 'PROTOCOL',  clue: 'Set of rules governing a blockchain application' },

  // ── 9-letter ──────────────────────────────────────────────────────────────
  { word: 'SIGNATURE',  clue: 'Cryptographic proof that you authorized a tx' },
  { word: 'VALIDATOR',  clue: 'Node that proposes and attests to blocks' },
  { word: 'DELEGATOR',  clue: 'Staker who assigns staking or voting power' },
  { word: 'LIQUIDATE',  clue: 'Force-sell collateral when health factor drops' },
  { word: 'FLASHLOAN',  clue: 'Uncollateralized loan borrowed and repaid in one tx' },
  { word: 'ALLOWANCE',  clue: 'Max tokens a spender is approved to move' },
  { word: 'OWNERSHIP',  clue: 'Control rights over a contract or NFT' },
  { word: 'COMMITTEE',  clue: 'Group of validators chosen for block attestation' },
  { word: 'EXECUTION',  clue: 'Running of smart contract logic on the EVM' },
  { word: 'SEQUENCER',  clue: 'L2 node that orders and batches transactions' },
  { word: 'LIQUIDITY',  clue: 'Assets available for trading or borrowing in a pool' },
  { word: 'IMMUTABLE',  clue: 'Value fixed at deploy time that cannot change' },
  { word: 'INTERFACE',  clue: 'Solidity abstract that defines contract methods' },
  { word: 'PAYMASTER',  clue: 'ERC-4337 contract that sponsors gas fees' },

  // ── 10-letter ─────────────────────────────────────────────────────────────
  { word: 'BLOCKCHAIN',  clue: 'Distributed ledger of cryptographically linked blocks' },
  { word: 'GOVERNANCE',  clue: 'On-chain voting and rule-making system for a DAO' },
  { word: 'SETTLEMENT',  clue: 'Final clearing of a transaction on the base layer' },
  { word: 'COLLATERAL',  clue: 'Assets pledged to secure a loan in DeFi' },
  { word: 'STABLECOIN',  clue: 'Token whose value is pegged to a stable asset' },
  { word: 'CROSSCHAIN',  clue: 'Spanning or interacting across multiple blockchains' },
];
