export interface WordEntry {
  word: string;
  clue: string;
}

export const WORD_BANK: WordEntry[] = [
  { word: 'GAS',      clue: 'Fee paid for blockchain transactions' },
  { word: 'NFT',      clue: 'Non-Fungible Token (abbr.)' },
  { word: 'DAO',      clue: 'Decentralized Autonomous Organization (abbr.)' },
  { word: 'ETH',      clue: 'Native currency of Ethereum' },
  { word: 'DEX',      clue: 'Decentralized exchange (abbr.)' },
  { word: 'CEX',      clue: 'Centralized exchange (abbr.)' },
  { word: 'APY',      clue: 'Annual percentage yield (abbr.)' },
  { word: 'TVL',      clue: 'Total value locked in a protocol (abbr.)' },
  { word: 'MEV',      clue: 'Value extracted by reordering txs (abbr.)' },
  { word: 'EVM',      clue: 'Ethereum Virtual Machine (abbr.)' },
  { word: 'ABI',      clue: 'Smart contract interface spec (abbr.)' },
  { word: 'RPC',      clue: 'Node communication protocol (abbr.)' },
  { word: 'ENS',      clue: 'Ethereum Name Service (abbr.)' },
  { word: 'RUG',      clue: 'Liquidity pull that wipes a token (slang)' },
  { word: 'FEE',      clue: 'Cost charged per transaction' },
  { word: 'KEY',      clue: 'Cryptographic secret for signing txs' },
  { word: 'AMM',      clue: 'Automated market maker (abbr.)' },
  { word: 'BASE',     clue: "Coinbase's L2 blockchain" },
  { word: 'MINT',     clue: 'Create a new NFT or token' },
  { word: 'SWAP',     clue: 'Exchange one token for another' },
  { word: 'POOL',     clue: 'Liquidity reserve for trading' },
  { word: 'EARN',     clue: 'Generate yield from crypto assets' },
  { word: 'BURN',     clue: 'Permanently destroy tokens' },
  { word: 'FORK',     clue: 'Split a blockchain into two chains' },
  { word: 'NODE',     clue: 'Network participant that validates txs' },
  { word: 'LOCK',     clue: 'Time-restrict access to tokens' },
  { word: 'BOND',     clue: 'Protocol-owned liquidity mechanism' },
  { word: 'VOTE',     clue: 'Governance action with locked tokens' },
  { word: 'WRAP',     clue: 'Tokenize a native asset (e.g. WETH)' },
  { word: 'PUMP',     clue: 'Sharp coordinated price increase (slang)' },
  { word: 'DUMP',     clue: 'Mass sell-off of a token (slang)' },
  { word: 'COLD',     clue: '___ wallet: offline key storage' },
  { word: 'SEED',     clue: 'Recovery phrase for a wallet' },
  { word: 'HASH',     clue: 'Cryptographic fingerprint of data' },
  { word: 'SAFE',     clue: 'Popular multisig wallet contract' },
  { word: 'DEFI',     clue: 'Decentralized Finance (abbr.)' },
  { word: 'HODL',     clue: 'Hold crypto no matter what (slang)' },
  { word: 'MEME',     clue: 'Viral token driven by internet culture' },
  { word: 'SIGN',     clue: 'Authorize a transaction with a private key' },
  { word: 'DROP',     clue: 'Short for airdrop' },
  { word: 'DEGEN',    clue: 'High-risk crypto trader (slang)' },
  { word: 'YIELD',    clue: 'Return earned from staking or lending' },
  { word: 'STAKE',    clue: 'Lock tokens to earn rewards' },
  { word: 'TOKEN',    clue: 'Digital asset on a blockchain' },
  { word: 'VAULT',    clue: 'Smart contract that holds funds securely' },
  { word: 'CHAIN',    clue: 'Sequence of linked transaction blocks' },
  { word: 'LAYER',    clue: '___ 2: scaling solution built on L1' },
  { word: 'PROXY',    clue: 'Upgradeable smart contract pattern' },
  { word: 'AUDIT',    clue: 'Security review of smart contract code' },
  { word: 'WHALE',    clue: 'Holder of an enormous amount of crypto' },
  { word: 'NONCE',    clue: 'Number used once for transaction ordering' },
  { word: 'BLOCK',    clue: 'Bundle of transactions added to the chain' },
  { word: 'PROOF',    clue: '___ of stake: consensus mechanism' },
  { word: 'CLAIM',    clue: 'Collect an airdrop or protocol reward' },
  { word: 'RELAY',    clue: 'Gasless transaction forwarder service' },
  { word: 'AURA',     clue: 'Onchain identity score on Base' },
  { word: 'WALLET',   clue: 'Software that stores your crypto keys' },
  { word: 'BRIDGE',   clue: 'Move assets between blockchains' },
  { word: 'DEPLOY',   clue: 'Publish a smart contract to the chain' },
  { word: 'PERMIT',   clue: 'Gasless token approval via signature' },
  { word: 'REVOKE',   clue: 'Cancel a token spending approval' },
  { word: 'ORACLE',   clue: 'Off-chain data feed for smart contracts' },
  { word: 'ROLLUP',   clue: 'L2 that batches txs and posts proofs to L1' },
  { word: 'ESCROW',   clue: 'Contract holding funds until conditions met' },
  { word: 'REWARD',   clue: 'Incentive paid to stakers or validators' },
  { word: 'FAUCET',   clue: 'Testnet dispenser of free tokens' },
  { word: 'STAKER',   clue: 'One who locks tokens for yield' },
  { word: 'SIGNER',   clue: 'Address authorized to sign transactions' },
  { word: 'MERKLE',   clue: '___ tree: data structure for proofs' },
  { word: 'AIRDROP',  clue: 'Free token distribution to holders' },
  { word: 'ONCHAIN',  clue: 'Stored or executed on a blockchain' },
  { word: 'TESTNET',  clue: 'Sandbox blockchain for development' },
  { word: 'MAINNET',  clue: 'Live production blockchain network' },
  { word: 'GENESIS',  clue: 'The very first block of a blockchain' },
  { word: 'ETHEREUM', clue: 'The second-largest smart contract platform' },
  { word: 'SNAPSHOT', clue: 'Record of balances at a specific block' },
  { word: 'MULTISIG', clue: 'Wallet requiring multiple signers to approve' },
  { word: 'BYTECODE', clue: 'Compiled EVM smart contract instructions' },
  { word: 'APPROVAL', clue: 'Permission granted to spend your tokens' },
];
